### ISSUE TITLE
Unable to import an app into Qlik core

### ISSUE THREAD

**Issue by sakaga** [qlik-oss/core#8]
I have a .qvf file and I am trying to import .qvf file into qlik core engine. 
Import API is [here](https://core.qlik.com/services/qix-engine/apis/rest/qlik-associative-engine-api/#post-v1appsimport)

I am not including license keys and corresponding docker code
My docker-compose is mentioned below:-

```
version: "3.0"
services:
  qix-engine:
    image: qlikcore/engine:12.268.0
    container_name: qix-engine-test
    command: -S AcceptEULA=yes -S EnableABAC=0
    volumes:
      - C:/Users/USER/Documents/DOCKER/dockerdata/qlik/apps:/home/nobody/apps
      - C:/Users/USER/Documents/DOCKER/dockerdata/qlik/certs:/home/nobody/certs
      - C:/Users/USER/Documents/DOCKER/dockerdata/qlik/abac:/home/nobody/abac
    ports:
      - 19076:9076
      - 9090:9090
      - 9098:80
    labels:
      qix-engine: "qix-engine-test"
```

and index.js :--

```
const rp = require('request-promise');
const fs = require('fs');
(async () => {
var options = {
    method: 'POST',
    uri: 'http://0.0.0.0:9076/v1/apps/import?name=test.qvf&mode=new',
    body: fs.createReadStream("C:/Users/username/Documents/Qlik/Sense/Apps/qlikcore.qvf")
};
rp(options)
    .then(function (parsedBody) {
        console.log('parsedBody', parsedBody)
    })
    .catch(function (err) {
        console.log(err.message)
    });
})();
```

Output is 
`parsedBody {"appId":"1cab98bb-a636-44bc-be74-5a24e992be49","attributes":{"name":"QlikCore","description":"","thumbnail":"","tags":[],"lastReloadTime":"2018-11-15T12:28:5.923Z","createdDate":""},"meta":{"Name":""}}`

```
/home/nobody/Qlik $ ls
Sense
/home/nobody/Qlik $ cd Sense/
/home/nobody/Qlik/Sense $ ls
Apps        Content     Extensions  Log         Temp
/home/nobody/Qlik/Sense $ cd Apps/
/home/nobody/Qlik/Sense/Apps $ ls
Search
```

**I cannot see my imported apps.**

- Where can I see imported apps?
- Is it necessary to use license image? 
- Is it possible to run this code without license key?
